apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: secret-app-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"  # Принудительное использование HTTPS
spec:
  tls:
  - hosts:
    - localhost
    secretName: secret-app-tls  # Имя TLS-секрета
  rules:
  - host: localhost
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: secret-app-api
            port:
              number: 80
